// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckStore.Infrastructure.Data;

#nullable disable

namespace TruckStore.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TruckStoreContext))]
    partial class TruckStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TruckStore.Domain.Brands.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1252b355-e2ab-4009-a1a2-7113c2589975"),
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = new Guid("3fb7a059-648e-4d96-a1ac-f76ab65d9c8d"),
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = new Guid("75f9efb7-07fb-4a66-a0d5-e2bb026c54e7"),
                            Name = "Iveco"
                        },
                        new
                        {
                            Id = new Guid("e89cde87-f6e4-4c1b-88e2-5827a9941867"),
                            Name = "Scania"
                        },
                        new
                        {
                            Id = new Guid("0310acb8-e043-4950-9626-5f27c2c897db"),
                            Name = "Renault"
                        });
                });

            modelBuilder.Entity("TruckStore.Domain.Trucks.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("maxLiftingCapacity")
                        .HasColumnType("int");

                    b.Property<int>("maxSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("TruckStore.Domain.Trucks.Truck", b =>
                {
                    b.HasOne("TruckStore.Domain.Brands.Brand", "BrandName")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandName");
                });
#pragma warning restore 612, 618
        }
    }
}
